# Generated by Django 3.2.5 on 2022-04-18 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('loginTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Login Time')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.level', verbose_name='Education level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'email', 'loginTime')},
            },
        ),
    ]
