# Generated by Django 3.2.5 on 2022-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
