# Generated by Django 3.2.5 on 2022-04-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='loginMethod',
            field=models.CharField(choices=[('email', 'By Email'), ('code', 'By Code')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
