# Generated by Django 3.2.5 on 2022-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
