# Generated by Django 3.2.5 on 2022-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(max_length=100),
        ),
    ]
