# Generated by Django 3.2.5 on 2022-04-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0013_alter_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.level', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
