# Generated by Django 3.2.5 on 2022-05-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220503_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(help_text="You have to update and overwite this field value , If You successfully changed the User's password", max_length=100),
        ),
    ]
