# Generated by Django 3.2.5 on 2022-05-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(help_text="You have to update and overwite this field value , If You successfully changed the User's password ONLY !!!", max_length=100),
        ),
    ]
