# Generated by Django 3.2.5 on 2022-05-07 09:51

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_raw_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'All Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/defaults/avatar.svg', null=True, upload_to='media/profile_images/%y/%m/%d', validators=[courses.validators.validate_image_file_extension]),
        ),
    ]
