# Generated by Django 3.2.5 on 2022-04-18 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(default=0, max_length=11)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=500)),
                ('respond', models.TextField(blank=True, null=True, verbose_name='Reply')),
                ('isSeen', models.BooleanField(default=False, verbose_name='Seen')),
                ('deliverdTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Delivered Time')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('sender', 'email', 'phone', 'subject', 'message')},
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelCode', models.CharField(choices=[('1P', '1ST_PREP'), ('2P', '2ND_PREP'), ('3P', '3RD_PREP'), ('1S', '1ST_SEC'), ('2S', '2ND_SEC'), ('3S', '3RD_SEC')], max_length=10)),
                ('levelFullName', models.CharField(choices=[('1st preparatory', '1ST PREPARATORY'), ('2nd preparatory', '2ND PREPARATORY'), ('3rd preparatory', '3RD PREPARATORY'), ('1st secondary', '1ST SECONDARY'), ('2nd secondary', '2ND SECONDARY'), ('3rd secondary', '3RD SECONDARY')], max_length=25)),
                ('numberOfLevelInLetters', models.CharField(choices=[('one', 'ONE'), ('two', 'TWO'), ('three', 'THREE')], default=0, max_length=10)),
                ('levelNameInLetters', models.CharField(choices=[('primary', 'PRIMARY'), ('preparatory', 'PREPARATORY'), ('secondary', 'SECONDARY')], default=0, max_length=15)),
                ('color', models.CharField(default='#64bcf4', max_length=15, verbose_name='Card Color')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Education level',
                'ordering': ['id'],
                'unique_together': {('levelCode', 'levelFullName'), ('levelNameInLetters', 'numberOfLevelInLetters')},
            },
        ),
    ]
