# Generated by Django 3.2.5 on 2022-05-14 13:46

import courses.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(null=True, upload_to='media/photos/%y/%m/%d', validators=[courses.validators.validate_image_file_extension], verbose_name='Symbol')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='#64bcf4', max_length=15, verbose_name='Card Color')),
                ('active', models.BooleanField(default=True)),
                ('creationTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
