# Generated by Django 3.2.5 on 2022-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='symbol',
            field=models.CharField(max_length=30, verbose_name='Symbol'),
        ),
    ]
