# Generated by Django 3.2.5 on 2022-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_subject_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='symbol',
            field=models.CharField(choices=[('fa-solid fa-book-open-cover', 'Arabic'), ('fa-solid fa-flask-vial', 'Chemistry'), ('fa-solid fa-lambda', 'Physics'), ('fa-solid fa-book', 'English'), ('fa-solid fa-circle', 'Geometry'), ('fa-solid fa-angle', 'Trignometry'), ('fa-solid fa-square-root-variable', 'Algebra'), ('fa-solid fa-chart-pie', 'Statistics')], max_length=50, verbose_name='Symbol'),
        ),
    ]
