# Generated by Django 3.2.5 on 2022-04-18 14:51

import courses.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/defaults/photo-1429043794791-eb8f26f44081.jpeg', null=True, upload_to='media/photos/%y/%m/%d', validators=[courses.validators.validate_image_file_extension], verbose_name='Thumbnail')),
                ('branch', models.CharField(choices=[('algebra', 'ALGEBRA'), ('trignometry', 'TRIGNOMETRY'), ('geometry', 'GEOMETRY')], max_length=25, verbose_name='category')),
                ('sourceLink', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=True)),
                ('creationTime', models.DateTimeField(default=datetime.datetime.now)),
                ('gradeLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.level')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regesterTime', models.DateTimeField(default=datetime.datetime.now)),
                ('lecture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=0, upload_to='media/files/%Y/%m/%d/', validators=[courses.validators.validate_file_extension])),
                ('branch', models.CharField(choices=[('algebra', 'ALGEBRA'), ('trignometry', 'TRIGNOMETRY'), ('geometry', 'GEOMETRY')], max_length=25, verbose_name='category')),
                ('uploadTime', models.DateTimeField(default=datetime.datetime.now)),
                ('isActive', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.level')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('file', 'lecture')},
            },
        ),
    ]
