# Generated by Django 3.2.5 on 2022-05-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_subject'),
        ('courses', '0002_alter_registeredlecture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.subject', verbose_name='category'),
        ),
    ]
